version: '3.8'

services:
  open-sora:
    image: spinnernicholas/open-sora:latest
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    volumes:
      - /workspace:/workspace
    ports:
      - "3000:3000"
    restart: unless-stopped